version = "3.8.4"

runner.dialect = scala3

maxColumn = 120
indent.main = 2
indent.significant = 2
indent.callSite = 2
indent.ctrlSite = 4
indent.defnSite = 4
indent.caseSite = 4

align.preset = more
align.multiline = false

newlines.source = keep
newlines.beforeCurlyLambdaParams = multilineWithCaseOnly
newlines.afterCurlyLambdaParams = squash

rewrite.rules = [
  RedundantBraces,
  RedundantParens,
  SortModifiers,
  PreferCurlyFors
]

rewrite.redundantBraces.methodBodies = false
rewrite.redundantBraces.includeUnitMethods = true
rewrite.redundantBraces.stringInterpolation = true

docstrings.style = Asterisk
docstrings.oneline = unfold

project.excludeFilters = [".*\\.sbt"]